version: '3.8'

services:
  polling-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BEE_API_URL=http://localhost:8080

    restart: unless-stopped